# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: publish cli.rs
env:
  MACOSX_DEPLOYMENT_TARGET: '10.13'
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-clirs]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            ext: ''
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            ext: ''
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            ext: '.exe'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Setup Rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.rust_target }}
          
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.config.rust_target }}

      - name: install MacOS dependencies
        if: matrix.config.os == 'macos-latest'
        run: |
          xcode-select --install
          brew tap homebrew/versions
          brew install protobuf
          brew install gcc7 --use-llvm
          brew install rocksdb
          
      - name: install Windows dependencies
        if: matrix.config.os == 'windows-latest'
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build CLI
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./Cargo.toml --release

      - name: Upload CLI
        uses: actions/upload-artifact@v3
        with:
          name: qdrant-${{ matrix.config.rust_target }}${{ matrix.config.ext }}
          path: target/release/qdrant${{ matrix.config.ext }}
          if-no-files-found: error

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download built CLIs
        uses: actions/download-artifact@v3
        with:
          path: outputs

      - name: Pack archives
        run: ./tools/pack-cli.sh

      - name: Publish release
        uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
        with:
          files: |
            outputs/qdrant-*.zip
            outputs/qdrant-*.tgz
